apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: postgres-values
    files:
      - values.yaml=values.yaml
