# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
global:
  postgresql:
    postgresqlDatabase: "wildlifedb"
postgresqlDatabase: wildlifedb
postgresqlUsername: postgres
postgresqlPassword: p@ssw0rd
