apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
  namespace: podinfo
data:
  application.yml: |
    server:
      port: 8888
    spring:
      jpa:
        hibernate:
          ddl-auto: create
      datasource:
        platform: postgres
        password: p@ssw0rd
        username: postgres
        url: jdbc:postgresql://postgresql:5432/wildlifedb
