apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
  namespace: podinfo
  labels:
    app: animals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: animals
        image: vivswam2021/snowflake:1.0.1
        #command: [ "/bin/sh", "-c", "env" ]
        ports:
          - containerPort: 8888
        env:
          - name: POSTGRES_SERVICE
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres.service.name
          - name: POSTGRES_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres.db.name
          - name: POSTGRES_DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db.user.name
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db.user.password
