apiVersion: v1
kind: Service
metadata:
  name: postgresvc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.pgport }}
  selector:
    app: {{ .Values.label }}
  clusterIP: None
